# 所有瞄准策略共用的弹丸与发射机构参数
/**:
  ros__parameters:
    bullet_speed_mps: 11.6
    drag_coefficient: 0.29 # 阻力系数
    gravity_mps2: 9.794
    air_density_kgpm3: 1.169
    bullet_mass_kg: 0.041
    bullet_radius_m: 0.02125
    muzzle_offset_m: 0.28 # 枪口到发射点距离
    ballistic_iteration_count: 10 # 弹道迭代次数
